name: CI/CD - Build, Push, and Deploy ECR; Build and Deploy FE

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: whiteboard

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

        # To ensure runner can build the container's arm64 infra
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to ECR
        id: push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Deploy New Image via SSM
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
          DB_IP: ${{ secrets.DB_SERVER_PRIVATE_IP }}
        run: |
          REDIS_ADDR="${DB_IP}:6379" 
          MONGO_URI="mongodb://${DB_IP}:27017/whiteboard"

          cat > deploy_params.json <<EOF
          {
            "InstanceIds": ["$INSTANCE_ID"],
            "DocumentName": "AWS-RunShellScript",
            "TimeoutSeconds": 3600,
            "Comment": "Automated deployment from GitHub Actions",
            "Parameters": {
              "commands": [
                "set -e",
                "echo \"Starting deployment for $IMAGE_URI\"",
                "aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY",
                "sudo docker pull $IMAGE_URI",
                "sudo docker rm -f server || true",
                "sudo docker run -d -p 8080:8080 \\
                  -e ENV=production \\
                  -e ALLOWED_ORIGINS=https://bwal.sh,https://walshyb.github.io \\
                  -e REDIS_ADDR=$REDIS_ADDR \\
                  -e MONGO_URI=$MONGO_URI \\
                  --name server $IMAGE_URI",
                  
                "echo \"Deployment complete.\""
              ]
            },
            "CloudWatchOutputConfig": {
              "CloudWatchOutputEnabled": true
            }
          }
          EOF

          # Send the command to the EC2 instance via SSM
          aws ssm send-command \
            --cli-input-json file://deploy_params.json \
            --region ${{ env.AWS_REGION }}

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "25.2"

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "25.2"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Setup Tools and Build Frontend
        env:
          VITE_WS_URL: ${{ secrets.API_URL }}
        run: |
          echo "Starting frontend build process..."

          # 1. Install Dependencies (Runs inside /client)
          cd client
          echo "Installing NPM dependencies (including TypeScript compiler) in client/"
          npm ci

          # 2. Generate Protobufs (Runs inside /)
          cd .. # Go back to root
          echo "Running 'make' command in root folder to generate Protobufs..."
          make proto_ts

          # 3. Build Frontend (Runs inside /client)
          cd client
          echo "Running 'npm run build' command..."
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist
          branch: gh-pages
